### ISSUE TITLE
获取转发信息很慢

### ISSUE THREAD

**Issue by fengmk2** [TBEDP/tjob#3]
打开职位详细页[/job/2](http://taojob.tbdata.org/job/2) ，发现获取转发人员信息很慢，无法选择转发人的情况下，投递简历，会出现一下异常：

```
Error: Column 'introducer' cannot be null
    at Function._packetToUserObject (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/client.js:342:7)
    at Query._handlePacket (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/query.js:35:33)
    at Client._handlePacket (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/client.js:294:14)
    at Parser.<anonymous> (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/client.js:83:14)
    at Parser.emit (events.js:42:17)
    at /usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/parser.js:75:14
    at Parser.write (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/parser.js:580:7)
    at Socket.<anonymous> (/usr/lib/node/.npm/mysql/0.9.1/package/lib/mysql/client.js:63:16)
    at Socket.emit (events.js:42:17)
    at Socket._onReadable (net.js:649:14)
```

**Comment by fengmk2** [comment]
已暂时屏蔽实时获取数据
